version: '3.9'

services:
  catalog-db:
    image: postgres:17
    container_name: catalog-db
    environment:
      POSTGRES_USER: catalog_user
      POSTGRES_PASSWORD: catalog_password
      POSTGRES_DB: catalog_db
    ports:
      - "5433:5432"
    volumes:
      - catalog_data:/var/lib/postgresql/data

  seating-db:
    image: postgres:17
    container_name: seating-db
    environment:
      POSTGRES_USER: seating_user
      POSTGRES_PASSWORD: seating_password
      POSTGRES_DB: seating_db
    ports:
      - "5434:5432"
    volumes:
      - seating_data:/var/lib/postgresql/data

  order-db:
    image: postgres:17
    container_name: order-db
    environment:
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: order_password
      POSTGRES_DB: order_db
    ports:
      - "5435:5432"
    volumes:
      - order_data:/var/lib/postgresql/data

  payment-db:
    image: postgres:17
    container_name: payment-db
    environment:
      POSTGRES_USER: payment_user
      POSTGRES_PASSWORD: payment_password
      POSTGRES_DB: payment_db
    ports:
      - "5436:5432"
    volumes:
      - payment_data:/var/lib/postgresql/data

  catalog-service:
    build: ../catalogservice
    container_name: catalog-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://catalog-db:5432/catalog_db
      SPRING_DATASOURCE_USERNAME: catalog_user
      SPRING_DATASOURCE_PASSWORD: catalog_password
    depends_on:
      - catalog-db

  seating-service:
    build: ../seatingservice
    container_name: seating-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://seating-db:5432/seating_db
      SPRING_DATASOURCE_USERNAME: seating_user
      SPRING_DATASOURCE_PASSWORD: seating_password
    depends_on:
      - seating-db

  order-service:
    build: ../orderservice
    container_name: order-service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://order-db:5432/order_db
      SPRING_DATASOURCE_USERNAME: order_user
      SPRING_DATASOURCE_PASSWORD: order_password
      CATALOG_SERVICE_URL: http://catalog-service:8081
      SEATING_SERVICE_URL: http://seating-service:8082
      PAYMENT_SERVICE_URL: http://payment-service:8084
    depends_on:
      - order-db
      - catalog-service
      - seating-service
      - payment-service

  payment-service:
    build: ../paymentservice
    container_name: payment-service
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://payment-db:5432/payment_db
      SPRING_DATASOURCE_USERNAME: payment_user
      SPRING_DATASOURCE_PASSWORD: payment_password
    depends_on:
      - payment-db

volumes:
  catalog_data:
  seating_data:
  order_data:
  payment_data:
